# Generated by Django 3.2.12 on 2024-03-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storemgt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='UOM',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='item_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
